#!/bin/sh


set -e

# Remove the "hold" mark on any package, in Kali we put kernel packages
# on hold because upgrading them hurts more than it helps  and  because
# we want to ensure they are not removed by a routine dist-upgrade.
in-target "apt-mark showhold | xargs apt-mark unhold"
